Repository impaulintech/barclerk, pull requests merged in 2022-11, with the labels that each got.

#1 [BarClerk-537] - [BE] Create User Sign-Up API
  api/app/Http/Controllers/Auth/SignUpController.php
  api/app/Http/Controllers/UserController.php
  api/app/Http/Requests/Auth/SignInRequest.php
  api/app/Http/Requests/Auth/SignUpRequest.php
  api/app/Http/Requests/UpdateUserRequest.php
  api/app/Http/Resources/UserResource.php
  api/app/Models/User.php
  api/database/migrations/2014_10_12_000000_create_users_table.php
  api/routes/api.php
  api/routes/auth.php
Labels: Dependent, For Code Review, Approved by Juswaa 💯

#5 [BarClerk-548] - [BE] Create User Sign In and Sign out API
  api/app/Http/Controllers/Auth/AuthController.php
Labels: For Code Review, Approved by AJ ✅

#6 [BarClerk-549] - [Markup] Create User Sign-In Page
  client/hooks/authMethods.ts
  client/pages/sign-in.tsx
  client/pages/sign-up.tsx
  client/shared/types/index.ts
Labels: For Code Review, Approved by AJ ✅

#7 [BarClerk-550] - [FE] Integrate User Sign-In API
  client/components/molecules/CustomForm/index.tsx
  client/pages/sign-in.tsx
  client/shared/types/index.ts
  client/shared/validation/index.ts
Labels: For Code Review, Approved by AJ ✅

#8 [BarClerk-553] - [Markup] Create Password reset page
  client/components/atoms/Button/index.tsx
  client/components/molecules/CustomForm/index.tsx
  client/components/templates/AdminAuthTemplate/index.tsx
  client/components/templates/MaintenancePage/index.tsx
  client/hooks/authMethods.ts
  client/hooks/useRememberMe.tsx
  client/pages/404.tsx
  client/pages/forgot-password.tsx
  client/pages/index.tsx
  client/pages/sign-in.tsx
  client/pages/sign-up.tsx
  client/public/favicon.ico
  client/public/images/lawgo.png
  client/public/images/logo-dark-transparent.png
  client/public/images/logo-light.png
  client/public/images/logo-transparent.png
  client/shared/types/index.ts
  client/shared/validation/index.ts
  client/styles/globals.css
  client/tailwind.config.js
Labels: For Code Review 💻

#9 [BarClerk-551] - [FE] Implement Route Protection
  README.md
  client/pages/forgot-password.tsx
  client/pages/index.tsx
  client/pages/sign-in.tsx
  client/pages/sign-up.tsx
  client/utils/getServerSideProps.ts
Labels: For Code Review 💻

#10 [BarClerk-552] - [BE] Create user forgot password API.
  api/app/Http/Controllers/Auth/ForgotPasswordController.php
  api/app/Http/Requests/ForgotPasswordRequest.php
  api/app/Http/Resources/ForgotPasswordResource.php
  api/routes/api.php
  api/routes/user/auth.php
  api/routes/user/user.php
  client/pages/forgot-password.tsx
  client/utils/getServerSideProps.ts
Labels: For Code Review 💻

#11 [BarClerk-554] - [FE] Integrate user forgot password API.
  client/components/templates/AdminAuthTemplate/index.tsx
  client/hooks/authMethods.ts
  client/hooks/useRememberMe.tsx
  client/package.json
  client/pages/forgot-password.tsx
  client/pages/sign-in.tsx
  client/pages/sign-up.tsx
  client/redux/auth/authService.ts
  client/redux/auth/authSlice.ts
  client/shared/types/index.ts
  client/utils/customSwal.ts
  client/utils/redirect.ts
  client/yarn.lock
Labels: For Code Review 💻

#13 [BarClerk-934] - [BE] Implement Create new Clients/matters API
  api/app/Http/Controllers/ClientController.php
  api/app/Http/Requests/Client/StoreClientRequest.php
  api/app/Models/Charge.php
  api/app/Models/Client.php
  api/app/Models/User.php
  api/app/Utils/ChargeUtils.php
  api/database/migrations/2022_11_08_133942_create_clients_table.php
  api/database/migrations/2022_11_08_135436_create_charges_table.php
  api/routes/api.php
  api/routes/web.php
Labels: Approved by John ✅, Approved by Joshua ✅, For Code Review 💻

#14 [BarClerk-931] - [BE] Create Get all clients/matter API
  api/app/Http/Controllers/ClientController.php
  api/app/Http/Resources/ChargeResource.php
  api/app/Http/Resources/ClientResource.php
  api/app/Providers/AppServiceProvider.php
  api/routes/api.php
Labels: Dependent, Approved by John ✅, Approved by Joshua ✅, For Code Review 💻

#15 [BarClerk-783] - [BE] Create search clients/matter name API
  api/app/Http/Controllers/ClientController.php
  api/app/Models/Client.php
Labels: Dependent, Approved by John ✅, Approved by Joshua ✅, For Code Review 💻

#18 [BarClerk-932] - [Markup] Create Home page
  client/package.json
  client/public/logo.svg
  client/public/vercel.svg
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/MenuTransition/index.tsx
  client/src/components/atoms/Pagination/index.tsx
  client/src/components/atoms/Skeletons/LineSkeleton.tsx
  client/src/components/molecules/CustomForm/index.tsx
  client/src/components/molecules/MainDashboardList/TableHead.tsx
  client/src/components/molecules/MainDashboardList/TableItem.tsx
  client/src/components/molecules/MainDashboardList/TableSkeleton.tsx
  client/src/components/molecules/MainDashboardList/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/helpers/.rm
  client/src/helpers/handleImageError.tsx
  client/src/hooks/authMethods.ts
  client/src/pages/404.tsx
  client/src/pages/_document.tsx
  client/src/pages/forgot-password.tsx
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/pages/sign-up.tsx
  client/src/shared/css/globals.css
  client/src/shared/css/tailwind.css
  client/src/shared/data/matters.ts
  client/src/shared/icons/LogoIcon.tsx
  client/src/shared/icons/Sorticon.tsx
  client/src/shared/interfaces/index.ts
  client/src/utils/skeletonAnimation.ts
  client/tailwind.config.js
  client/yarn.lock
Labels: Approved by John ✅, For Code Review 💻

#19 [BarClerk-935] - [Markup] Create Client input info modal
  client/package.json
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/components/molecules/MainTableHeader/index.tsx
  client/src/components/templates/DialogBox/index.tsx
  client/src/pages/index.tsx
  client/src/shared/icons/CourtChargeIcon.tsx
  client/src/shared/icons/CourtHouseIcon.tsx
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/yarn.lock
Labels: For Code Review 💻

#20 [BarClerk-340] - [Markup] - Add Client Field to Modal
  client/package.json
  client/src/components/molecules/MainDashboardList/TableHead.tsx
  client/src/components/molecules/MainDashboardList/TableItem.tsx
  client/src/components/molecules/MainDashboardList/index.tsx
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/pages/index.tsx
  client/src/shared/css/globals.css
  client/src/shared/data/matters.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/yarn.lock
Labels: For Code Review 💻

#21 [BarClerk-933] - [FE] Implement Fetch, Filter, and Search Matter Functionality
  api/app/Enums/MatterStatusEnum.php
  api/app/Enums/PreTrialRestrictionEnum.php
  api/app/Http/Controllers/ClientController.php
  api/app/Http/Requests/Client/StoreClientRequest.php
  api/app/Http/Resources/ClientListResource.php
  api/app/Http/Resources/MatterStatusResource.php
  api/app/Http/Resources/PreTrialRestrictionResource.php
  api/app/Models/Client.php
  api/app/Models/ClientPreTrialRestriction.php
  api/app/Models/MatterStatus.php
  api/app/Models/PreTrialRestriction.php
  api/database/migrations/2022_11_08_133942_create_clients_table.php
  api/database/migrations/2022_11_12_150456_create_pre_trial_restrictions_table.php
  api/database/migrations/2022_11_12_152014_create_client_pre_trial_restriction_table.php
  api/database/migrations/2022_11_13_074210_create_matter_statuses_table.php
  api/database/migrations/2022_11_13_075812_add_status_to_clients_table.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/MatterStatusSeeder.php
  api/database/seeders/PreTrialRestrictionSeeder.php
  api/routes/api.php
  api/routes/web.php
  client/src/components/atoms/Pagination/index.tsx
  client/src/components/molecules/MainDashboardList/TableItem.tsx
  client/src/components/molecules/MainDashboardList/index.tsx
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/components/molecules/MainTableHeader/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/hooks/authMethods.ts
  client/src/hooks/searchDebounce.ts
  client/src/pages/index.tsx
  client/src/redux/auth/authSlice.ts
  client/src/redux/matter/matterService.ts
  client/src/redux/matter/matterSlice.ts
  client/src/redux/matter/types.ts
  client/src/redux/store.ts
  client/src/shared/data/matters.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/types/pageTypes.ts
  client/src/shared/validation/index.ts
  client/src/utils/constants.ts
  client/src/utils/getServerSideProps.ts
Labels: Approved by Joshua ✅, For Code Review 💻

#22 [BarClerk-134] - [Markup] Create Settings page
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/molecules/UserSettingsModal/ActiveTabComponent.tsx
  client/src/components/molecules/UserSettingsModal/DialogHeader.tsx
  client/src/components/molecules/UserSettingsModal/index.tsx
  client/src/pages/index.tsx
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: For Code Review 💻

#23 [BarClerk-091] - [Markup] Create Client Layout Page
  client/package.json
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/organisms/MatterDrawer/index.tsx
  client/src/components/organisms/MatterHeader/index.tsx
  client/src/components/organisms/MatterSidebar/index.tsx
  client/src/components/templates/MatterLayout/index.tsx
  client/src/pages/matter/[id]/court-appearances.tsx
  client/src/pages/matter/[id]/grant-of-aid.tsx
  client/src/pages/matter/[id]/index.tsx
  client/src/pages/matter/[id]/time-entries.tsx
  client/src/shared/icons/CourtAppearancesIcon.tsx
  client/src/shared/icons/DashboardIcon.tsx
  client/src/shared/icons/GrantOfAidIcon.tsx
  client/src/shared/icons/TimeEntriesIcon.tsx
  client/src/shared/lib/next-progress.tsx
  client/yarn.lock
Labels: For Code Review 💻

#24 [BarClerk-936] - [FE] Integrate Create new Clients/matters API
  api/routes/user/user.php
  client/src/components/molecules/UserSettingsModal/ActiveTabComponent.tsx
  client/src/redux/auth/authService.ts
  client/src/redux/auth/authSlice.ts
Labels: For Code Review

#25 [BarClerk-937] - [FE] Integrate Create new Clients/matters API
  api/app/Enums/PageEnum.php
  api/app/Http/Controllers/ClientController.php
  api/app/Http/Requests/Client/StoreClientRequest.php
  api/app/Models/Client.php
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/hooks/useMatter.ts
  client/src/redux/matter/matterService.ts
  client/src/redux/matter/matterSlice.ts
  client/src/redux/matter/types.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/src/utils/constants.ts
Labels: Approved by Joshua ✅, For Code Review 💻

#26 [BarClerk-938] - [Markup] Create GOL Page
  client/src/components/atoms/Breedcrumb/index.tsx
  client/src/components/molecules/GrantOfAidCard/index.tsx
  client/src/components/molecules/GrantOfAidList/index.tsx
  client/src/components/molecules/MainDashboardList/TableItem.tsx
  client/src/components/organisms/MatterSidebar/index.tsx
  client/src/components/templates/MatterLayout/index.tsx
  client/src/pages/matter/[id]/client-profile.tsx
  client/src/pages/matter/[id]/grant-of-aid.tsx
  client/src/shared/data/grantOfAidData.ts
  client/src/shared/interfaces/index.ts
Labels: For Code Review 💻

#29 [BarClerk-947] - [Markup] Create Client Profile page
  client/src/components/atoms/SeeMore/index.tsx
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/pages/matter/[id]/client-profile.tsx
  client/src/shared/interfaces/index.ts
  client/tailwind.config.js
Labels: For Code Review 💻
