Repository impaulintech/barclerk, pull requests merged in 2022-12, with the labels that each got.

#31 [BarClerk-939] - [BE] Implement Add, Edit, and Delete functions for GOL API
  api/app/Enums/ClauseEnum.php
  api/app/Http/Controllers/ClauseController.php
  api/app/Http/Controllers/GrantController.php
  api/app/Http/Requests/GrantRequest.php
  api/app/Http/Resources/ClauseResource.php
  api/app/Http/Resources/ClauseTypeResource.php
  api/app/Http/Resources/GrantResource.php
  api/app/Models/Clause.php
  api/app/Models/Client.php
  api/app/Models/Grant.php
  api/app/Models/Type.php
  api/app/Utils/CodeTypeUtils.php
  api/database/json/clauses.json
  api/database/json/types.json
  api/database/migrations/2022_11_30_072827_create_clauses_table.php
  api/database/migrations/2022_11_30_103642_create_types_table.php
  api/database/migrations/2022_12_01_095322_create_grants_table.php
  api/database/migrations/2022_12_01_101008_create_grant_codes_table.php
  api/database/seeders/ClauseSeeder.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/TypeSeeder.php
  api/routes/api.php
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
Labels: Approved by John ✅, For Code Review 💻, Approved by Juswaa 💯

#32 [BarClerk-940] - [BE] Implement Add, and Edit Time Entry info API
  api/app/Enums/PageEnum.php
  api/app/Http/Controllers/ExtensionController.php
  api/app/Http/Controllers/TimeEntryController.php
  api/app/Http/Requests/TimeEntryRequest.php
  api/app/Http/Resources/ExtensionResource.php
  api/app/Http/Resources/TimeEntryResource.php
  api/app/Models/Client.php
  api/app/Models/Grant.php
  api/app/Models/GrantCode.php
  api/app/Models/TimeEntry.php
  api/database/migrations/2022_12_03_072324_create_time_entries_table.php
  api/routes/api.php
Labels: Approved by Joshua ✅, For Code Review 💻

#33 [BarClerk-943] - [BE] Implement Create, Update and Get Court Appearances API
  api/app/Enums/PageEnum.php
  api/app/Http/Controllers/CourtAppearanceController.php
  api/app/Http/Requests/CourtAppearanceRequest.php
  api/app/Http/Resources/CourtAppearanceResource.php
  api/app/Models/Client.php
  api/app/Models/CourtAppearance.php
  api/database/migrations/2022_12_03_132936_create_court_appearances_table.php
  api/routes/api.php
Labels: Approved by Joshua ✅, For Code Review 💻

#30 [BarClerk-944] - [Markup] Create court appearances page with modal
  client/package.json
  client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
  client/src/components/molecules/CourtAppearanceAccordion/index.tsx
  client/src/components/molecules/CourtAppearanceList/AddNewCourtAppearance.tsx
  client/src/components/molecules/CourtAppearanceList/index.tsx
  client/src/hooks/useCourtAppearance.ts
  client/src/pages/matter/[id]/court-appearances.tsx
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/yarn.lock
Labels: AJ is Reviewing 🔎, For Code Review 💻, Approved by Juswaa 💯

#34 [BarClerk-946] - [BE] Create Get all clients/matter info in profile page API
  api/app/Http/Controllers/ClientController.php
  api/app/Http/Controllers/DashboardController.php
  api/app/Http/Controllers/DashboardExtensionController.php
  api/app/Http/Resources/DashboardResource.php
  api/app/Models/Client.php
  api/routes/api.php
Labels: Approved by Joshua ✅, For Code Review 💻

#27 [BarClerk-960] - [Markup] Create input GOL modal
  client/package.json
  client/src/components/molecules/GrantOfAidCard/index.tsx
  client/src/components/molecules/GrantOfAidList/AddNewGrantOfAidModal.tsx
  client/src/components/molecules/GrantOfAidList/EditGrantOfAidModal.tsx
  client/src/components/molecules/GrantOfAidList/ViewCodeModal.tsx
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/pages/matter/[id]/grant-of-aid.tsx
  client/src/shared/css/globals.css
  client/src/shared/data/codesData.ts
  client/src/shared/data/grantOfAidData.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
  client/yarn.lock
Labels: Approved by AJ ✅, For Code Review 💻

#37 [BarClerk-690] - [BE/FE] Create and Integrate Preparation, Others, and Court Attendance API
  api/app/Http/Controllers/DashboardExtensionController.php
  api/app/Models/Client.php
  api/app/Models/Grant.php
  api/app/Models/TimeEntry.php
Labels: Approved by Joshua ✅, For Code Review 💻

#38 [BarClerk-046] - [BE] Create a validation rule to check whether creating a new time entry is valid
  api/app/Http/Requests/TimeEntryRequest.php
  api/app/Models/Client.php
  api/app/Models/Grant.php
  api/app/Rules/HasRemainingFunds.php
Labels: Approved by Joshua ✅, For Code Review 💻

#39 [BarClerk-048] - [FE] Add Actual Data to the Main Dashboard table
  api/app/Http/Resources/ClientListResource.php
  api/app/Http/Resources/GrantResource.php
  api/app/Models/Client.php
  client/src/components/molecules/MainDashboardList/TableHead.tsx
  client/src/components/molecules/MainDashboardList/TableItem.tsx
  client/src/shared/interfaces/index.ts
Labels: Approved by Joshua ✅, For Code Review 💻

#36 [BarClerk-948] - [FE] Integrate Get all clients/matter info in profil…
  api/app/Models/Client.php
  client/src/components/molecules/ClientProfileCard/CardSkeleton.tsx
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
  client/src/components/molecules/CourtAppearanceAccordion/index.tsx
  client/src/pages/matter/[id]/client-profile.tsx
  client/src/redux/client-profile/clientProfileSlice.ts
  client/src/redux/store.ts
  client/src/shared/interfaces/index.ts
Labels: For Code Review, Approved by Joshua ✅, Work-In-Progress, Don't merge

#40 [BarClerk-942] - [FE] Integrate Add, and Edit Time Entry info API
  api/app/Http/Requests/TimeEntryRequest.php
  api/database/migrations/2022_12_03_072324_create_time_entries_table.php
  client/src/components/molecules/TimeEntriesTable/Pagination/index.tsx
  client/src/components/molecules/TimeEntriesTable/TableHead.tsx
  client/src/components/molecules/TimeEntriesTable/TableItem.tsx
  client/src/components/molecules/TimeEntriesTable/index.tsx
  client/src/components/molecules/TimeEntryTableHeader/AddNewEntry.tsx
  client/src/components/molecules/TimeEntryTableHeader/index.tsx
  client/src/components/templates/DialogBox/index.tsx
  client/src/hooks/useNewEntry.ts
  client/src/pages/matter/[id]/time-entries.tsx
  client/src/redux/time-entry/timeEntryService.ts
  client/src/redux/time-entry/timeEntrySlice.ts
  client/src/shared/validation/index.ts
Labels: For Code Review 💻

#35 [BarClerk-146] - [FE] Integrate Add Edit and Delete function for GOL
  api/app/Http/Resources/GrantResource.php
  api/app/Models/Client.php
  api/app/Models/Grant.php
  client/src/components/atoms/Breedcrumb/index.tsx
  client/src/components/atoms/Skeletons/CardSkeleton.tsx
  client/src/components/atoms/Skeletons/InputSkeleton.tsx
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/components/molecules/GrantOfAidCard/index.tsx
  client/src/components/molecules/GrantOfAidList/AddNewGrantOfAidModal.tsx
  client/src/components/molecules/GrantOfAidList/EditGrantOfAidModal.tsx
  client/src/components/molecules/GrantOfAidList/Pagination.tsx
  client/src/components/molecules/GrantOfAidList/ViewCodeModal.tsx
  client/src/components/molecules/GrantOfAidList/index.tsx
  client/src/components/molecules/MainTableHeader/AddNewMatterModal.tsx
  client/src/components/molecules/UserSettingsModal/index.tsx
  client/src/components/organisms/MatterDrawer/index.tsx
  client/src/components/templates/DialogBox/DialogBox2.tsx
  client/src/hooks/useGrantOfAid.ts
  client/src/pages/_document.tsx
  client/src/pages/matter/[id]/client-profile.tsx
  client/src/pages/matter/[id]/grant-of-aid.tsx
  client/src/redux/grant-of-aid/grantOfAidService.ts
  client/src/redux/grant-of-aid/grantOfAidSlice.ts
  client/src/redux/grant-of-aid/interface.ts
  client/src/redux/store.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: Approved by John ✅, For Code Review 💻, Approved by Juswaa 💯

#43 [BarClerk-945] - [FE] Integrate Create, Update and Get Court Appearan…
  api/composer.json
  api/composer.lock
  api/database/migrations/2022_12_10_064742_update_other_notes_column_in_court_appearances_table.php
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
  client/src/components/molecules/CourtAppearanceAccordion/index.tsx
  client/src/components/molecules/CourtAppearanceList/AddNewCourtAppearance.tsx
  client/src/components/molecules/CourtAppearanceList/index.tsx
  client/src/hooks/useCourtAppearance.ts
  client/src/pages/matter/[id]/client-profile.tsx
  client/src/pages/matter/[id]/court-appearances.tsx
  client/src/redux/client-profile/clientProfileSlice.ts
  client/src/redux/court-appearance/courtAppearanceSlice.ts
  client/src/redux/store.ts
  client/src/shared/interfaces/index.ts
  client/src/shared/types/index.ts
  client/src/shared/validation/index.ts
Labels: For Code Review, Approved by Joshua ✅, Approved by Juswaa 💯

#44 [BarClerk-991] - [Bugtask] Set limit to three Court Appearance items …
  client/src/components/molecules/ClientProfileCard/index.tsx
Labels: bug, For Code Review

#45 [BarClerk-990] - [Bugtask] Fix Edit Dynamic Code Fields
  client/src/components/molecules/GrantOfAidList/AddNewGrantOfAidModal.tsx
  client/src/components/molecules/GrantOfAidList/EditGrantOfAidModal.tsx
  client/src/shared/validation/index.ts
  client/src/utils/customReactSelectStyles.ts
  client/tailwind.config.js
Labels: For Code Review 💻, 🐛 bug-task

#49 [BarClerk-992] - [Bugtask] Make next court date value dynamic based o…
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/redux/client-profile/clientProfileSlice.ts
Labels: bug, For Code Review

#51 [270] - [BugTask] Add Sum of Preparation for a Specific Extension in the Client Dashboard
  api/app/Models/Client.php
  api/database/json/types.json
  client/src/components/molecules/ClientProfileCard/index.tsx
  client/src/shared/interfaces/index.ts
Labels: For Code Review 💻, 🐛 bug-task

#55 Update cour appearances and fix issues
  api/app/Http/Requests/CourtAppearanceRequest.php
  api/database/migrations/2022_12_10_064742_update_other_notes_column_in_court_appearances_table.php
  client/src/components/molecules/CourtAppearanceAccordion/EditCourtAppearanceModal.tsx
  client/src/components/molecules/CourtAppearanceList/AddNewCourtAppearance.tsx
  client/src/hooks/useCourtAppearance.ts
  client/src/shared/validation/index.ts
Labels: For Code Review 💻

#60 Password change redirect to login
  client/src/hooks/authMethods.ts
Labels: For Code Review 💻
